# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 102fad4e2666c134b468488a81b5d49d66a8ededd23513d017c31de9fe15c4d7730bf94473f723119f09a3f03c8652dbc12077b164f5a30ebb3b8015c8ac2273

test:
  secret_key_base: 341c16fcef196e2a93b0d4f09bd7c2e5e03577a5fb78347658fcc973bea0155fff035a254e9eb69b2781f04b68257330d3093ba68e8fe21843989d5babe27b3f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
